WILLing-Application/willing

- pom.xml
- src/main/java/dev/willingapp/willing/controllers/HelloController.java
Remove security from pom.xml (temporarily)
Update HelloController from /home to /hello
> Comment security dependencies, update controller for /hello page

- src/main/java/dev/willingapp/willing/models/Album.java
- src/main/java/dev/willingapp/willing/models/Interest.java
- src/main/java/dev/willingapp/willing/models/Invite.java
- src/main/java/dev/willingapp/willing/models/Item.java
- src/main/java/dev/willingapp/willing/models/User.java
Created:
- User model
- Album model
- Item model
- Interest model
- Invite model
Was able to run the application and run sql queries for table info
> Aaron models

- src/main/java/dev/willingapp/willing/models/Album.java
- src/main/java/dev/willingapp/willing/models/Comment.java
- src/main/java/dev/willingapp/willing/models/Image.java
- src/main/java/dev/willingapp/willing/models/Item.java
- src/main/java/dev/willingapp/willing/models/User.java
Feat:
- Added Image and Comment models/entities.
- added cascade = CascadeType.all to @OneToMany's
> Aaron comment images models

- README.md
Readme now has: Features List, User stories, Additional features list, URL and Methods maps
> filled out readme file and is updatable

- src/main/java/dev/willingapp/willing/controllers/UserController.java
- src/main/java/dev/willingapp/willing/models/User.java
- src/main/java/dev/willingapp/willing/models/UserWithRoles.java
- src/main/java/dev/willingapp/willing/repositories/UserRepository.java
- src/main/java/dev/willingapp/willing/services/SecurityConfiguration.java
- src/main/java/dev/willingapp/willing/services/UserDetailsLoader.java
Setup security with some basic routes requiring login.
Implemented BCrypt with salt of 12
> Implement Spring Boot Security

- README.md
- src/main/java/dev/willingapp/willing/controllers/UserController.java
- src/main/java/dev/willingapp/willing/models/User.java
- src/main/java/dev/willingapp/willing/services/SecurityConfiguration.java
- src/main/resources/templates/partials/navbar.html
- src/main/resources/templates/users/login.html
- src/main/resources/templates/users/sign-up.html
Updated Readme file with latest version of user stories, features, and part of the URL Methods mapping.
Got the spring security working for the sign-up page, to where you can register for an account, it's saved to the database, and you're redirected to "/" for now.
Login page isn't working yet, but I have to stop & work on placement deliverables.
> Update readme file & got sign-up working

- .gitignore
- src/main/java/dev/willingapp/willing/controllers/TestController.java
- src/main/resources/static/js/filestack.js
- src/main/resources/templates/partials/head.html
- src/main/resources/templates/partials/scripts.html
- src/main/resources/templates/testing/test-images.html
- src/main/resources/willing_db.setup.sql
Following updates:
> created TestController
> created  templates/testing/test-images.html
> created js/filestack.js
> added Filestack API CDN to head.html
> added filestack.js and keys.js scripts to scripts.html
> Aaron filestack

- src/main/java/dev/willingapp/willing/controllers/UserController.java
- src/main/resources/templates/partials/head.html
- src/main/resources/templates/users/login.html
- src/main/resources/willing_db.setup.sql
Updated controller to fix login route
Updated head partial with page title placeholder & added it to login
> Fix login and head partial

- src/main/resources/templates/items/edit.html
- src/main/resources/templates/items/index.html
- src/main/resources/templates/items/items.html
- src/main/resources/templates/partials/navbar.html
- src/main/resources/templates/view.html
items pages created minus its create page(Aaron) nav pointing to new page
> George branch

- src/main/java/dev/willingapp/willing/controllers/ItemController.java
- src/main/java/dev/willingapp/willing/models/Item.java
- src/main/resources/static/js/filestack.js
- src/main/resources/templates/items/items-create.html
Updated:
- Created ItemController 
added ItemRepo and ImageRepo dependency injections
added a @GetMapping("/items/create") and @PostMapping("/items/create")
-Created items-create.html
-Added a constructor in Item class
> created ItemController and items-create.html

- src/main/resources/static/js/example_keys.js
File to show how to setup the API key for Filestack
> add example file to show filestack API key is needed

- src/main/java/dev/willingapp/willing/controllers/ItemController.java
- src/main/resources/templates/items/item.html
made changes to ItemController and item.html
> added delete functionality for items

- src/main/java/dev/willingapp/willing/controllers/AuthenticationController.java
- src/main/java/dev/willingapp/willing/controllers/ProfileController.java
- src/main/java/dev/willingapp/willing/controllers/UserController.java
- src/main/java/dev/willingapp/willing/models/User.java
- src/main/resources/templates/profile.html
Updating profile in a stable non-broken state
Made changes to user authentication while trying to fix sign-up allowing empty form fields (not finished)
> Laura user profile

- src/main/resources/templates/partials/panel-profile.html
- src/main/resources/templates/users/profile.html
matrix added to page, navigation from nav may need fixing, could not navigate to it after merging and before adding
> added targets in matrix and target in profile view

- src/main/java/dev/willingapp/willing/controllers/ProfileController.java
- src/main/resources/templates/users/profile.html
Reverts working user profile page, had to comment out panel-profile.
Please pull down and re-test integration.
Sorry :(
> Fix conflict with panel-profile partial

- src/main/resources/WILLing_db_seeder.sql
Add seeder to github for use in production 
Commented out images table load
> edited and add db seeder to git

- src/main/java/dev/willingapp/willing/controllers/AlbumController.java
- src/main/java/dev/willingapp/willing/controllers/ItemController.java
- src/main/resources/templates/albums/add-guest.html
- src/main/resources/templates/albums/albums.html
- src/main/resources/templates/albums/show.html
- src/main/resources/templates/items/item.html
Added owner privilege functionality where guests cannot crud an album they are invited to. Also added feature where the owner can't add the same guest twice on an album.
> added owner privilege functionality

- src/main/java/dev/willingapp/willing/controllers/ViewController.java
- src/main/java/dev/willingapp/willing/repositories/AlbumRepository.java
- src/main/resources/templates/view.html
Table is in place in view.html, needs selection fx next
> table added to view page controller and repos adjusted

- README.md
- src/main/java/dev/willingapp/willing/controllers/ProfileController.java
- src/main/java/dev/willingapp/willing/models/User.java
- src/main/resources/templates/users/delete.html
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/profile.html
Updated readme user stories to reflect scope and changes, updated features list:
-moved email invites to optional features, 
-updated interest ranking to 1-3,
-removed email/username/password from user CRUD.
User profile Edit is functional, except for uploading a profile photo.
User profile Delete is not throwing errors but doesn't delete the user from the database.
> Laura edit profile

- src/main/java/dev/willingapp/willing/controllers/ProfileController.java
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/profile.html
- src/main/resources/templates/users/sign-up.html
Added feature to where users can upload their profile picture and will have a placeholder pic if otherwise.
> Aaron profile

- src/main/resources/templates/albums/albums.html
- src/main/resources/templates/dev-profile.html
> Fix closing tags on navbar partial

- src/main/resources/templates/dev-profile.html
- src/main/resources/templates/users/delete.html
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/login.html
- src/main/resources/templates/users/profile.html
- src/main/resources/templates/users/sign-up.html
Add pre header on profile pages
Remove Junior from devs titles
Add bootstrap styling to form pages
> Laura header

- src/main/resources/static/css/login.css
- src/main/resources/templates/home.html
- src/main/resources/templates/users/login.html
Added new class to login.css to target message text on login page
Fixed font awesome icon in footer on login page
I don't think I changed the home page, just reformatted with Opt+Cmd+L to better find the fa link to copy/paste...
> home & login fontawesome icons & font color

- src/main/resources/templates/users/delete.html
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/profile.html
Swapped out the header to apply consistent navbar, brand, etc to profile view/edit/delete pages.
Have more work to do but trying to keep it in small pieces so I don't break things! :)
> apply new header style to profile pages (Part 1)

- src/main/resources/static/css/index.css
- src/main/resources/templates/albums/albums.html
- src/main/resources/templates/albums/show.html
Added classes on albums.html and show.html to change font color. Also added those classes on index.css.
> changed font colors on the red buttons on albums and items pages

- src/main/resources/static/js/panels.js
- src/main/resources/templates/view.html
view page styled and arranged - there's plenty of white space when there are no albums in desktop mode, works decent in mobil
> view page styled and arranged

- src/main/resources/static/css/profile.css
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/sign-up.html
Minor change to sign-up page input type on Phone
Styling on the profile Edit page
> Laura profile edit

- src/main/resources/templates/albums/add-guest.html
> styling to add guest page complete

- src/main/resources/templates/view.html
> view page overlap fixed

- src/main/resources/static/css/profile.css
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/profile.html
Last styling bits for the profile
> remove delete button, styling profile view and edit

- src/main/resources/templates/items/items-create.html
- src/main/resources/templates/view.html
> create item page styled

- src/main/resources/templates/albums/create.html
> album create page done

- src/main/resources/static/css/profile.css
- src/main/resources/templates/users/profile.html
Make the text on the profile view a little larger
> increase font size on profile view

- src/main/resources/templates/view.html
> View page rearrange George matrix

- src/main/resources/static/css/login.css
- src/main/resources/static/css/profile.css
- src/main/resources/templates/error/4xx.html
- src/main/resources/templates/users/profile.html
Upped the text size and fiddled with placement
> profile view restyle, larger text

- src/main/java/dev/willingapp/willing/services/SecurityConfiguration.java
- src/main/resources/static/css/index.css
- src/main/resources/static/css/profile.css
- src/main/resources/templates/users/edit.html
- src/main/resources/templates/users/profile.html
- src/main/resources/templates/users/sign-up.html
Route to /profile after login
Style profile view (Get Started & Account Details) text and padding
Style profile edit (button width)
Bump up footer font size
Add footer to sign-up page
> Laura style tweaks

- README.md
- src/main/resources/static/css/index.css
Fix hamburger icon and update readme.
> Laura home about

- src/main/resources/templates/view.html
2 Files:
view.html
ViewController
> view page and view controller UX changes
